export const FETCH_SEARCH_LOADING = "FETCH_SEARCH_LOADING";
export const FETCH_MORE_RESULTS_LOADING = "FETCH_MORE_RESULTS_LOADING";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_ERROR = "FETCH_SEARCH_ERROR";
